---
- name: Collect grub cmdline options
  command: sed -n 's/GRUB_CMDLINE_LINUX="\(.*\)"/\1/p' /etc/default/grub
  register: docker__r_grub_cmdline
  changed_when: false
  check_mode: no
  args:
    warn: false

- name: Enable user namespace in kernel
  lineinfile: dest=/etc/default/grub regexp='^{{item.key}}' line='{{item.key}}="{{docker__r_grub_cmdline.stdout.split() | union(item.add) | difference(item.del) | join(" ")}}"' owner=root group=root mode=0644
  loop:
    - key: GRUB_CMDLINE_LINUX
      add:
        - 'user_namespace.enable=1'
        - 'namespace.unpriv_enable=1'
      del: []
  register: docker__r_grub

- block:
  - name: Regenerate grub configuration
    command: grub2-mkconfig -o /boot/grub2/grub.cfg

  - name: Restart server
    shell: sleep 5 && /sbin/shutdown -r now "Reboot triggered by Ansible"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for reboot
    wait_for_connection: delay=30

  when: docker__r_grub.changed

- name: Add namespace mapping files
  lineinfile: dest={{item}} state=present create=yes owner=root group=root mode=0600 regexp='^dockremap:.*' line='dockremap:165536:65536'
  loop:
    - /etc/subuid
    - /etc/subgid
  notify: Restart docker

- name: Add userns-remap option to docker daemon
  set_fact:
    docker_config: '{{docker_config | combine({"userns-remap": "default"})}}'

- name: Increase max_user_namespaces
  sysctl: name=user.max_user_namespaces value=15076 state=present
  when: ansible_distribution_version is version("7.4", ">=")
